from __future__ import annotations

from enum import Enum


class CycleOutcome(str, Enum):
    SUCCESS = "SUCCESS"
    TEST_FAILURE = "TEST_FAILURE"
    BUILD_FAILURE = "BUILD_FAILURE"
    PATCH_REJECTED = "PATCH_REJECTED"
    PLAN_INVALID = "PLAN_INVALID"
    CAPABILITY_DENIED = "CAPABILITY_DENIED"
    TIME_BUDGET_EXCEEDED = "TIME_BUDGET_EXCEEDED"
    STEP_LIMIT_EXCEEDED = "STEP_LIMIT_EXCEEDED"
    NO_EFFECT_DIFF = "NO_EFFECT_DIFF"
    FAILED = "FAILED"
    REPLAY_DENIED = "REPLAY_DENIED"
    WORKSPACE_DRIFT_DENIED = "WORKSPACE_DRIFT_DENIED"
